name: DebugEconomy
version: '${version}'
main: me.lorenzo0111.debugeconomy.DebugEconomy
api-version: 1.13
depend: [Vault]
authors: [Lorenzo0111]
commands:
  debugeconomy:
    aliases: [de,eco]
    permission: economy.debug
    permission-message: You need the economy.debug permission to use this command.